Algoritmo "Temperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Converter celsius em Farenheit, o usuário deverá inserir a temperatura.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2022
Var
c, f : real

Inicio
      escreva ("Digite a temperatura em celsius:")
      leia (c)
      f<-((c*9)/5)+32);
      escreva("a temperatura de celsius é igual á" , f ,"  em Fahrenheit é")
Fimalgoritmo