Algoritmo "Antecessor"
// Descrição   : Desenvolver um programa onde o usuário insira um número e devolva seu antecessor e sucessor.
// Autor(a)    : Yasmim Katari
// Data atual  : 27/03/2022
Var

n, a, s:real

Inicio
        Escreva ("Digite o número:")
        leia (n)
        a <- n-1;
        s <- n+1;
        escreva ( a, " é o antecessor, e " , s , "  é o sucessor")
Fimalgoritmo