Algoritmo "Chuva"
// Disciplina   : Algoritmos
// Descrição   : 1 polegada = 25,4 mililitros; Fazer um algoritmo que leia a quantia de chuva em polegadas e mostre o equivalente em mililitro.
// Autor(a)    : Yasmim Katari
// Data atual  : 27/03/2022
Var
         chuva, totalp: real
Inicio
           escreva (" Aquantidade de chuva em polegadas:")
           leia (chuva)
           totalp <- chuva * 25.4;
           escreva("A quantidade de chuva em polegadas é" ,totalp)
Fimalgoritmo